site_name: PROJECT_NAME Documentation
site_description: Complete PROJECT_NAME documentation  
site_url: https://GITHUB_USERNAME.github.io/PROJECT_NAME/

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Guides: guides/
  - API Reference: api/
  - Tutorials: tutorials/

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/GITHUB_USERNAME/PROJECT_NAME
    - icon: fontawesome/solid/globe
      link: https://GITHUB_USERNAME.github.io/PROJECT_NAME/